# Generated by Django 6.0.3 on 2026-03-15 14:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['roll_number']},
        ),
        migrations.AddField(
            model_name='mark',
            name='exam_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mark',
            name='score',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('student', 'subject', 'exam_date')},
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['student'], name='students_ma_student_cb5904_idx'),
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['subject'], name='students_ma_subject_a93db2_idx'),
        ),
    ]
